// Generated by Cypress Author on 2026-09-29.

// Signed out, the gated areas must show a sign-in prompt and no private content.
describe('Gated areas when signed out', () => {
  it('open /family → asks the visitor to sign in and calls no photo API', () => {
    // Fail loudly if the page ever asks for photos without a session.
    cy.intercept('GET', 'https://api.cohns.net/family/**', cy.spy().as('familyApi'))

    cy.visitPage('/family/')
    cy.contains('Sign in to view the family library.')
    // Scope to the gallery: the page shell has a static empty lightbox <img>.
    cy.get('#gallery img').should('not.exist')
    cy.get('@familyApi').should('not.have.been.called')
  })

  it('open /admin → asks the visitor to sign in and lists no users', () => {
    cy.visitPage('/admin/')
    cy.contains('Sign in to manage access.')
    cy.contains('button', /grant|revoke/i).should('not.exist')
  })

  it('open the auth bar → offers a Sign in button', () => {
    cy.visitPage('/')
    cy.get('#authbar').contains('button, a', 'Sign in')
  })
})
