// Generated by Cypress Author on 2026-09-29.

describe('Site navigation', () => {
  it('home → foodie → recipes → back to foodie → classes', () => {
    cy.visit('/')

    // Home panel links into the foodie hub
    cy.contains('a', 'Recipes & classes').click()
    cy.location('pathname').should('eq', '/foodie/')
    cy.get('h1').should('have.text', "I'm a foodie")

    cy.contains('a', 'Browse recipes').click()
    cy.location('pathname').should('eq', '/recipes/')
    cy.get('h1').should('have.text', 'Recipes')

    cy.contains('a', "← I'm a foodie").click()
    cy.location('pathname').should('eq', '/foodie/')

    cy.contains('a', 'See classes').click()
    cy.location('pathname').should('eq', '/classes/')
    cy.get('h1').should('contain.text', 'Classes')
  })

  it('home → résumé → back to home', () => {
    cy.visit('/')
    cy.contains('a', 'Résumé').click()
    cy.location('pathname').should('eq', '/resume/')
    cy.contains('a', 'Back to cohns.net').click()
    cy.location('pathname').should('eq', '/')
  })

  it('home → external links point at the expected destinations', () => {
    cy.visit('/')
    // Only check hrefs; never follow cross-origin links in a smoke suite.
    cy.contains('a', 'a public Terraform repository').should(
      'have.attr',
      'href',
      'https://github.com/steve-cohn-personal/cohns-net-infra'
    )
    cy.contains('a', 'steve@cohns.net').should('have.attr', 'href', 'mailto:steve@cohns.net')
  })
})
