// Generated by Cypress Author on 2026-09-29.

describe('Public pages', () => {
  const pages = [
    { path: '/', h1: 'Steven M. Cohn' },
    { path: '/foodie/', h1: "I'm a foodie" },
    { path: '/recipes/', h1: 'Recipes' },
    { path: '/classes/', h1: 'Classes & workshops' },
    { path: '/resume/', h1: 'Résumé' },
  ]

  pages.forEach(({ path, h1 }) => {
    it(`visit ${path} → responds 200 and shows its heading`, () => {
      cy.request(path).its('status').should('eq', 200)
      cy.visit(path)
      cy.get('h1').should('contain.text', h1)
    })
  })

  it('visit an unknown path → shows the custom 404 page', () => {
    cy.visit('/no-such-page', { failOnStatusCode: false })
    cy.contains('h1', 'No route to host')
    cy.contains('a', 'Back to the front page').should('have.attr', 'href', '/')
  })
})
