import { defineConfig } from 'cypress'

// Generated by Cypress Author on 2026-09-29.
//
// These specs run against the LIVE site. Default target is prod; specs under
// cypress/e2e/live-api/ are prod-only (dev has no API). Override
// with `--config baseUrl=https://dev.cohns.net` (see `npm run cy:run:dev`).
//
// This repo is PUBLIC. Never put a Cypress Cloud record key in this file —
// export CYPRESS_RECORD_KEY (locally) or use a GitHub secret (CI). The projectId
// is not a secret and is added by `cypress open` when you connect Cypress Cloud.
export default defineConfig({
  e2e: {
    baseUrl: 'https://cohns.net',
    specPattern: 'cypress/e2e/**/*.cy.ts',
    supportFile: 'cypress/support/e2e.ts',
    // The Aurora database scales to zero, so the first API call after idle can be slow.
    defaultCommandTimeout: 10000,
    responseTimeout: 30000,
    retries: { runMode: 2, openMode: 0 },
    video: false,
    screenshotOnRunFailure: true,
  },
})
