// Generated by Cypress Author on 2026-09-29.

declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Visit a page and wait for the shared auth bar to render, which is the
       * signal that the page's scripts have run.
       */
      visitPage(path: string): Chainable<void>
    }
  }
}

Cypress.Commands.add('visitPage', (path: string) => {
  cy.visit(path)
  cy.get('#authbar').should('not.be.empty')
})

export {}
