// Generated by Cypress Author on 2026-09-29.

// Read-only on purpose: signups and requests POST to prod and trigger an SNS
// email to Steve, so they are deliberately NOT exercised against the live site.
type ClassSession = { slug: string; title: string }

describe('Classes', () => {
  it('open the classes page → each class from the live API is listed', () => {
    cy.intercept('GET', 'https://api.cohns.net/classes*').as('classes')
    cy.visitPage('/classes/')

    cy.wait('@classes').then(({ response }) => {
      expect(response?.statusCode).to.eq(200)
      const classes = response?.body as ClassSession[]
      expect(classes, 'published classes').to.have.length.greaterThan(0)

      classes.forEach((c) => cy.contains('#class-list', c.title))
    })
  })
})
