// Generated by Cypress Author on 2026-09-29.

// Recipes are live content that Steve edits, so nothing here hard-codes a
// title: the API is queried first and the tests derive their expectations from it.
type Recipe = { slug: string; title: string; servings: number | null }

describe('Recipes', () => {
  const apiUrl = 'https://api.cohns.net'

  beforeEach(() => {
    cy.intercept('GET', `${apiUrl}/recipes*`).as('recipes')
    cy.request<Recipe[]>(`${apiUrl}/recipes`).then(({ body }) => {
      expect(body, 'published recipes').to.have.length.greaterThan(0)
      cy.wrap(body).as('apiRecipes')
    })
  })

  it('open the recipe list → every published recipe is shown as a card from the live API', function () {
    cy.visitPage('/recipes/')
    cy.wait('@recipes').its('response.statusCode').should('eq', 200)

    cy.get('.recipe-card').should('have.length', this.apiRecipes.length)
    // The bundled-sample fallback shows this note; seeing it means the API failed.
    cy.get('.demo-note').should('not.exist')
  })

  it('search for a recipe title → results narrow to matches and clearing restores the list', function () {
    const target: Recipe = this.apiRecipes[0]

    cy.visitPage('/recipes/')
    cy.get('.recipe-card').should('have.length', this.apiRecipes.length)

    cy.get('.recipe-search').type(target.title)
    cy.get('.recipe-card').should('have.length.lessThan', this.apiRecipes.length)
    cy.contains('.recipe-card', target.title).should('be.visible')

    cy.get('.recipe-search').clear()
    cy.get('.recipe-card').should('have.length', this.apiRecipes.length)
  })

  it('search for gibberish → shows the empty-results message', () => {
    cy.visitPage('/recipes/')
    cy.get('.recipe-card').should('exist')
    cy.get('.recipe-search').type('zzzxqvwy')
    cy.contains('No recipes match your search.')
    cy.get('.recipe-card').should('not.exist')
  })

  it('open a recipe card → detail page shows the title and ingredients', function () {
    const target: Recipe = this.apiRecipes[0]

    cy.visitPage('/recipes/')
    cy.contains('.recipe-card', target.title).click()

    cy.location('search').should('include', `slug=${target.slug}`)
    cy.contains('h1', target.title)
    cy.contains(/ingredients/i)
  })

  it('change the servings on a scalable recipe → the control updates and reset restores the original', function () {
    const target = (this.apiRecipes as Recipe[]).find((r) => r.servings && r.servings > 0)
    expect(target, 'a recipe with a servings value').to.exist

    cy.visitPage(`/recipes/recipe.html?slug=${target!.slug}`)

    cy.get('.servings-input').should('have.value', String(target!.servings))
    cy.get('button[aria-label="More servings"]').click()
    cy.get('.servings-input').should('have.value', String(target!.servings! + 1))

    cy.get('.servings-reset').click()
    cy.get('.servings-input').should('have.value', String(target!.servings))
  })
})
